modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/NoAI-Spawn-Eggs/issues"
license="LGPL v2.1"

[[mods]]
modId="noaispawneggs"
updateJSONURL="https://updates.blamejared.com/get?n=noaispawneggs&gv=1.16.3"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.noaispawneggs]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.noaispawneggs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="SERVER"