modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/NoAI-Spawn-Eggs/issues"

[[mods]]
modId="noaispawneggs"
updateJSONURL="https://updates.blamejared.com/get?n=noaispawneggs&gv=1.16.1"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.noaispawneggs]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.noaispawneggs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"