modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/NoAI-Spawn-Eggs/issues"

[[mods]]
modId = "noaispawneggs"
version = "26.1.2.0"
displayName = "NoAISpawnEggs"
updateJSONURL = "https://updates.blamejared.com/get?n=noaispawneggs&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/no-ai-spawn-eggs"
logoFile = "logo_noaispawneggs.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Spawn mobs quickly with no AI!"

[[mixins]]
config = "noaispawneggs.common.mixins.json"

[[mixins]]
config = "noaispawneggs.neoforge.mixins.json"

[[dependencies.noaispawneggs]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.noaispawneggs]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

